version: "3"
services:
  # PostgreSQL Database
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: database
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - my-network

  # Hasura GraphQL Engine
  hasura:
    container_name: hasura
    image: hasura/graphql-engine:latest
    environment:
      HASURA_GRAPHQL_DATABASE_URL: ${HASURA_GRAPHQL_DATABASE_URL}
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      HASURA_GRAPHQL_ENABLE_CONSOLE: ${HASURA_GRAPHQL_ENABLE_CONSOLE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h postgres -U $POSTGRES_USER"]
      interval: 2s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    networks:
      - my-network

  # Next.js Frontend
  nextjs:
    container_name: nextjs
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    depends_on:
      - hasura
    environment:
      NEXT_PUBLIC_HASURA_ADMIN_SECRET: ${HASURA_GRAPHQL_ADMIN_SECRET}
      NEXT_PUBLIC_HASURA_BASE_URL: http://localhost:8081/v1/graphql
      NEXT_PUBLIC_HASURA_WS_URL: ws://localhost:8081/v1/graphql
    ports:
      - "3000:3000"
    networks:
      - my-network

  # # Nginx
  # nginx:
  #   container_name: nginx
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - nextjs
  #     - hasura
  #     - expressjs
  #   networks:
  #     - my-network

networks:
  my-network:
